server:
  port: 8005

spring:
  application:
    name: myconsumer
  main: #允许多个feign调用相同的服务接口
    allow-bean-definition-overriding: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
